export {default as light} from './light.svg'
export {default as dark} from './dark.svg'
export {default as instagram} from './instagram.svg'
export {default as facebook} from './facebook.svg'
export {default as linkedin} from './linkedin.svg'
export {default as youtube} from './youtube.svg'